version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-browsers
      - image: circleci/python:3.7-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: make virtualenv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install django==2.2
            pip install tox
      - run:
          name: make sqlite3 db
          command: |
            . venv/bin/activate
            manage.py migrate
      - run:
          name: run tox
          enviroment:
            HEADLESS: True
          command: |
            . venv/bin/activate
            tox