version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-browsers
      - image: circleci/python:3.7-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: make virtualenv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/base-requirements.txt
            pip install tox
      - run:
          name: make sqlite3 db
          command: |
            . venv/bin/activate
            python3 security_headers.py migrate
      - run:
          name: run tox
          command: |
            . venv/bin/activate
            tox