version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1-node-browsers
      - image: circleci/python:3.7.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: make virtualenv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - run:
          name: run tox
          command: |
            . venv/bin/activate
            tox